package com.google.pizzahot.DB.tables;

import com.google.pizzahot.model.Location;
import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Алексей on 28.10.2016.
 */

public class LocationData {
    // id is generated by the database and set on the object automatically
    @DatabaseField(generatedId = true)
    private int id;

    @DatabaseField
    private double distance;

    @DatabaseField
    private double latitude;

    @DatabaseField
    private double longitude;

    @DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = "page_id")
    private VenueData page;

    public LocationData(Location location, VenueData page) {
        this.distance = location.getDistance();
        this.latitude = location.getLat();
        this.longitude = location.getLng();
        this.page = page;
    }

    LocationData() {
    }
}
